import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { SUPPORT_EMAIL } from "@/lib/support";

/**
 * NOTE FOR THE OWNER: plain-language terms matching how the product actually
 * behaves. Two things are assumptions you should confirm — the governing law
 * (Israel) and the 18+ age floor for purchases. Prices are deliberately not
 * repeated here so this page cannot contradict `TIERS` in src/lib/types.ts.
 * Not legal advice; have a lawyer review before marketing.
 */
export const metadata: Metadata = {
  title: "Terms of Service — SpeCV",
  description:
    "The agreement between you and SpeCV: what the service does, what you are responsible for, and how purchases work.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="27 July 2026">
      <p>
        By using SpeCV you agree to these terms. If you do not agree, please
        don&rsquo;t use the service. Questions:{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>

      <h2>What SpeCV does</h2>
      <p>
        You give us your CV and a job description. We use AI to produce a
        tailored one-page CV, a report of what changed and why, and interview
        preparation material. That is the whole service.
      </p>
      <p>
        SpeCV is <strong>not</strong> a recruitment agency, an employer, or a
        career, legal or immigration adviser. We do not submit applications on
        your behalf and{" "}
        <strong>
          we cannot promise interviews, offers, or any particular outcome.
        </strong>
      </p>

      <h2>AI output, and why you must read it</h2>
      <p>
        The output is generated by an AI model working from what you provided.
        It can contain mistakes: a rephrasing that overstates your experience, a
        wrong date, an invented detail. <strong>You are responsible</strong> for
        reviewing every CV before you send it to an employer, and for making
        sure everything in it is true. Never submit a generated CV you have not
        read.
      </p>

      <h2>Your account</h2>
      <p>
        You sign in with Google or GitHub. Keep that account secure — anything
        done through it counts as done by you. You must be 18 or older to make a
        purchase.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Use SpeCV for your own CV, or for someone who asked you to.</li>
        <li>
          Do not upload another person&rsquo;s personal data without their
          consent.
        </li>
        <li>
          Do not resell, bulk-generate, scrape, or attempt to extract our
          prompts or models, and do not work around usage limits.
        </li>
        <li>
          Do not use SpeCV to create deliberately false or fraudulent
          credentials.
        </li>
      </ul>
      <p>
        We may suspend an account that breaks these rules, or that costs us
        abnormal amounts of AI processing.
      </p>

      <h2>Who owns what</h2>
      <p>
        <strong>Your content stays yours</strong> — your CV, your answers, and
        the CVs we generate for you. You grant us the limited permission needed
        to process that content in order to deliver the service. The site,
        templates, prompts and software are ours.
      </p>

      <h2>Payments</h2>
      <p>
        Purchases are per job application, at the price shown at checkout, in US
        dollars. Payments are processed by Lemon Squeezy as seller of record;
        taxes are added by them where required. Access to what you bought is
        granted once their confirmation reaches us, which is normally immediate.
      </p>
      <p>
        Samples are watermarked and partly hidden on purpose — they are a
        preview, not a deliverable. See the{" "}
        <Link href="/refunds">refund policy</Link> for cancellations and
        failures.
      </p>

      <h2>Availability</h2>
      <p>
        SpeCV is an early-stage product offered as-is, with no uptime guarantee.
        Features can change or be removed. AI generation depends on third-party
        providers and can be slow or temporarily unavailable.
      </p>

      <h2>Limits on liability</h2>
      <p>
        To the extent the law allows, we are not liable for indirect or
        consequential losses — including a job you did not get, an offer you did
        not receive, or lost income. Our total liability to you is limited to
        the amount you paid us in the twelve months before the claim. Nothing
        here excludes liability that cannot legally be excluded, and your
        statutory consumer rights are unaffected.
      </p>

      <h2>Ending the agreement</h2>
      <p>
        You can stop at any time and delete your account and data from My
        Account.
        We may end your access if you break these terms. Deleting your account
        does not entitle you to a refund of a completed purchase, except as set
        out in the refund policy.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of Israel, and the courts of Tel
        Aviv-Yafo have jurisdiction — except where consumer law in your country
        of residence gives you the right to bring a claim locally.
      </p>

      <h2>Changes</h2>
      <p>
        We will update the date at the top of this page when these terms change,
        and email signed-in users about significant changes. Continuing to use
        SpeCV after a change means you accept it.
      </p>
    </LegalPage>
  );
}
